Projetos/ProjetoMoeda/ProjetoMoeda/Models/ErrorViewModel.cs
using System;

namespace ProjetoMoeda.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Projetos/ProjetoMoeda/ProjetoMoeda/Models/Moeda.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ProjetoMoeda.Models
{
    public class Moeda
    {
        public int MoedaId { get; set; }
        public string Nome { get; set; }
        public int Quantidade { get; set; }

        [NotMapped] //não será mapeado para o banco de dados
        public bool CheckboxMarcado { get; set; }
    }
}

Projetos/ProjetoMoeda/ProjetoMoeda/Models/MoedaContexto.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjetoMoeda.Models
{
    public class MoedaContexto:DbContext
    {
        public DbSet<Moeda> Moedas { get; set; } // contrunido o banco 'Moedas' é o nome do banco
        //contrutor
        public MoedaContexto(DbContextOptions<MoedaContexto> opcoes):base(opcoes)
        {

        }
    }
}

Projetos/ProjetoMoeda/ProjetoMoeda/Controllers/MoedasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjetoMoeda.Models;

namespace ProjetoMoeda.Controllers
{
    public class MoedasController : Controller
    {
        private readonly MoedaContexto _context;

        public MoedasController(MoedaContexto context)
        {
            _context = context;
        }

        // GET: Moedas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Moedas.ToListAsync());
        }

        public async Task<IActionResult> EscolhadeMoedas(List<Moeda> moedas)
        {
            foreach(var item in moedas)
            {
                if (item.CheckboxMarcado == true)
                {
                    Moeda moeda = await _context.Moedas.FindAsync(item.MoedaId);
                    moeda.Quantidade = moeda.Quantidade + 1;
                    _context.Update(moeda);
                    await _context.SaveChangesAsync();
                }
            }
            return RedirectToAction(nameof(Index));
        }

        public JsonResult dadosGrafico()
        {
            //retorna o resultado de nome e quant.
            return Json(_context.Moedas.Select(dado => new { dado.Nome, dado.Quantidade }));
        } 
        // GET: Moedas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Moedas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MoedaId,Nome,Quantidade")] Moeda moeda)
        {
            if (ModelState.IsValid)
            {
                moeda.Quantidade = 0; // quando o usuario criar a moeda,a quantidade é automatica Zero
                _context.Add(moeda);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(moeda);
        }

    }  
}

Projetos/ProjetoMoeda/ProjetoMoeda/ViewComponents/MoedasViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjetoMoeda.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjetoMoeda.ViewComponents
{
    public class MoedasViewComponent : ViewComponent
    {
        private readonly MoedaContexto _moedaContexto;
        public MoedasViewComponent(MoedaContexto moedaContexto)
        {
            _moedaContexto = moedaContexto;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            // retornar uma lista
            return View(await _moedaContexto.Moedas.ToListAsync());
        }
    }
}

Projetos/ProjetoMoeda/ProjetoMoeda/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projeto Moeda</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Moedas" asp-action="Index" class="navbar-brand">Projeto Moeda</a>
            </div>
            <div class="navbar-collapse collapse">
               
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
       
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/Chart.js/Chart.bundle.js"></script>
        <script src="~/lib/Chart.js/Chart.js"></script><!--Adicionado biblioteca Instalada-->
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/lib/Chart.js/Chart.bundle.js"></script>
        <script src="~/lib/Chart.js/Chart.min.js"></script><!--Adicionado biblioteca Instalada minificado-->
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>