Aulas/Aula11ConsultaBancodeDados/Aula11ConsultaBancodeDados/Models/Contexto.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Aula11ConsultaBancodeDados.Models
{
    public class Contexto: DbContext
    {
        public DbSet<UsuarioDB> UsuarioDB { get; set; }
        public Contexto(DbContextOptions<Contexto> options) : base(options) { }
    }
}

Aulas/Aula11ConsultaBancodeDados/Aula11ConsultaBancodeDados/Models/ErrorViewModel.cs
using System;

namespace Aula11ConsultaBancodeDados.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Aulas/Aula11ConsultaBancodeDados/Aula11ConsultaBancodeDados/Models/UsuarioDB.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Aula11ConsultaBancodeDados.Models
{
    public class UsuarioDB
    {
        [Key]
        public int UsuarioID { get; set; }
        public string NomeCompleto { get; set; }
        public int Idade { get; set; }
    }
}

Aulas/Aula11ConsultaBancodeDados/Aula11ConsultaBancodeDados/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Aula11ConsultaBancodeDados.Models;

namespace Aula11ConsultaBancodeDados.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Aulas/Aula11ConsultaBancodeDados/Aula11ConsultaBancodeDados/Controllers/UsuarioDBController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Aula11ConsultaBancodeDados.Models;

namespace Aula11ConsultaBancodeDados.Controllers
{
    public class UsuarioDBController : Controller
    {
        private readonly Contexto _context;

        public UsuarioDBController(Contexto context)
        {
            _context = context;
        }

        // GET: UsuarioDBs
        public async Task<IActionResult> Index()
        {
            return View(await _context.UsuarioDB.ToListAsync());
        }
        public async Task<IActionResult>Index(string txtProcurar)
        {
            if(!string.IsNullOrEmpty(txtProcurar)) // se txtProcurar não for vazio ou nulo
            {
                return View(await _context.UsuarioDB.Where(procura => procura.NomeCompleto.ToUpper().Contains(txtProcurar.ToUpper())).ToListAsync()); // toUpper, aceita letras caixa alta e baixa
            }
            else
            {
                
                return View(await _context.UsuarioDB.ToListAsync());
            }
        }

        // GET: UsuarioDBs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuarioDB = await _context.UsuarioDB
                .FirstOrDefaultAsync(m => m.UsuarioID == id);
            if (usuarioDB == null)
            {
                return NotFound();
            }

            return View(usuarioDB);
        }

        // GET: UsuarioDBs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: UsuarioDBs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UsuarioID,NomeCompleto,Idade")] UsuarioDB usuarioDB)
        {
            if (ModelState.IsValid)
            {
                _context.Add(usuarioDB);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(usuarioDB);
        }

        // GET: UsuarioDBs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuarioDB = await _context.UsuarioDB.FindAsync(id);
            if (usuarioDB == null)
            {
                return NotFound();
            }
            return View(usuarioDB);
        }

        // POST: UsuarioDBs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UsuarioID,NomeCompleto,Idade")] UsuarioDB usuarioDB)
        {
            if (id != usuarioDB.UsuarioID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usuarioDB);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioDBExists(usuarioDB.UsuarioID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usuarioDB);
        }

        // GET: UsuarioDBs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuarioDB = await _context.UsuarioDB
                .FirstOrDefaultAsync(m => m.UsuarioID == id);
            if (usuarioDB == null)
            {
                return NotFound();
            }

            return View(usuarioDB);
        }

        // POST: UsuarioDBs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usuarioDB = await _context.UsuarioDB.FindAsync(id);
            _context.UsuarioDB.Remove(usuarioDB);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsuarioDBExists(int id)
        {
            return _context.UsuarioDB.Any(e => e.UsuarioID == id);
        }
    }
}

Aulas/Aula11ConsultaBancodeDados/Aula11ConsultaBancodeDados/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Aula11ConsultaBancodeDados</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Aula11ConsultaBancodeDados</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - Aula11ConsultaBancodeDados</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Aulas/Aula11ConsultaBancodeDados/Aula11ConsultaBancodeDados/Views/UsuarioDB/Create.cshtml
@model Aula11ConsultaBancodeDados.Models.UsuarioDB

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>UsuarioDB</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NomeCompleto" class="control-label"></label>
                <input asp-for="NomeCompleto" class="form-control" />
                <span asp-validation-for="NomeCompleto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idade" class="control-label"></label>
                <input asp-for="Idade" class="form-control" />
                <span asp-validation-for="Idade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Aulas/Aula11ConsultaBancodeDados/Aula11ConsultaBancodeDados/Views/UsuarioDB/Delete.cshtml
@model Aula11ConsultaBancodeDados.Models.UsuarioDB

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UsuarioDB</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomeCompleto)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NomeCompleto)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Idade)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Idade)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="UsuarioID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Aulas/Aula11ConsultaBancodeDados/Aula11ConsultaBancodeDados/Views/UsuarioDB/Details.cshtml
@model Aula11ConsultaBancodeDados.Models.UsuarioDB

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>UsuarioDB</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomeCompleto)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NomeCompleto)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Idade)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Idade)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.UsuarioID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Aulas/Aula11ConsultaBancodeDados/Aula11ConsultaBancodeDados/Views/UsuarioDB/Edit.cshtml
@model Aula11ConsultaBancodeDados.Models.UsuarioDB

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>UsuarioDB</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="UsuarioID" />
            <div class="form-group">
                <label asp-for="NomeCompleto" class="control-label"></label>
                <input asp-for="NomeCompleto" class="form-control" />
                <span asp-validation-for="NomeCompleto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idade" class="control-label"></label>
                <input asp-for="Idade" class="form-control" />
                <span asp-validation-for="Idade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Aulas/Aula11ConsultaBancodeDados/Aula11ConsultaBancodeDados/Views/UsuarioDB/Index.cshtml
@model IEnumerable<Aula11ConsultaBancodeDados.Models.UsuarioDB>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="UsuarioDB" asp-action="Index" method="post">
<input class="form-control" name="txtProcurar" /><button type="submit">Procurar</button>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NomeCompleto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idade)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NomeCompleto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Idade)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.UsuarioID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.UsuarioID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.UsuarioID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>